export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const UPDATE_LOADING_TEXT = "UPDATE_LOADING_TEXT";

// USER LOGIN
export const TOGGLE_LOGGED_IN = "TOGGLE_LOGGED_IN";
export const TOGGLE_LOGIN_MODAL = "TOGGLE_LOGIN_MODAL";

// THIRD BIG WINDOW
export const FETCH_CHATS_START = 'FETCH_CHATS_START';
export const FETCH_CHATS_SUCCESS = 'FETCH_CHATS_SUCCESS';
export const FETCH_CHATS_FAILURE = 'FETCH_CHATS_FAILURE';

// FEATURES
export const SHOW_PROFILE = 'SHOW_PROFILE';
export const SHOW_SAVED_POSTS = 'SHOW_SAVED_POSTS';
export const SHOW_CONNECTIONS = 'SHOW_CONNECTIONS';
export const SHOW_CHATS = 'SHOW_CHATS';
export const SHOW_CREATE_BLOGS = 'SHOW_CREATE_BLOGS';
