export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const UPDATE_LOADING_TEXT = "UPDATE_LOADING_TEXT";

export const TOGGLE_LOGIN_MODAL = "TOGGLE_LOGIN_MODAL";
export const TOGGLE_LOGGED_IN = "TOGGLE_LOGGED_IN";
